package pl.put.poznan.rulework.enums;

public enum ClassifierType {
    SIMPLE_RULE_CLASSIFIER,
    SIMPLE_OPTIMIZING_COUNTING_RULE_CLASSIFIER,
    SCORING_RULE_CLASSIFIER_SCORE,
    SCORING_RULE_CLASSIFIER_HYBRID
}
